# [programs.mainnet]
# solvent_protocol = "SVTy4zMgDPExf1RaJdoCo5HvuyxrxdRsqF1uf2Rcd7J"

[programs.localnet]
solvent_protocol = "SVTy4zMgDPExf1RaJdoCo5HvuyxrxdRsqF1uf2Rcd7J"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/genesis-programs/mpl_token_metadata.so"

[[test.genesis]]
address = "nft3agWJsaL1nN7pERYDFJUf54BzDZwS3oRbEzjrq6q"
program = "./tests/genesis-programs/solvent.so"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# [provider]
# cluster = "https://ssc-dao.genesysgo.net/"
# wallet = "~/.config/solana/mainnet.json"

[scripts]
test = "yarn run ts-mocha --parallel -t 1000000 tests/**/*.ts"

[features]
seeds = true
